### ISSUE TITLE
Getting error updating from 1.2.1 to 1.2.2 - detectStart() not defined.

### ISSUE THREAD

**Issue by danzen** [ml5js/ml5-next-gen#274]
Getting an error that detectStart() is not a function when updating from 1.2.1 to 1.2.2.  This seems rather clumsy so maybe it is a bug in your code?  If not, what would we need to do to fix it.  Thanks.

<img width="555" height="92" alt="Image" src="https://github.com/user-attachments/assets/966d309a-7f63-4917-a79b-0194ce6034b9" />

<img width="865" height="95" alt="Image" src="https://github.com/user-attachments/assets/fa593d90-8292-4825-96b3-106c769a4a74" />

**Comment by danzen** [comment]
Thanks Daniel.
